name: Docker Image CI
on:
  push:
    branches: [ "Development" ]
jobs:
  build:
    runs-on:
      - win-dev
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd 'DockerTest\DockerTest'
        docker build .  -t dockerTest:latest
        cd 'C:\developing\docker\newApi'
        

        
