name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Generate Date-Time Tag
      run: echo "IMAGE_TAG=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mohamedoweis/ticketingsystem:$IMAGE_TAG
    - name: push image to docker hub
      run: |
          docker login -u mohamedoweis -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push mohamedoweis/ticketingsystem:$IMAGE_TAG  
    
    - name: Trigger Deployment on Server
      run: ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "docker pull mohamedoweis/ticketingsystem:$IMAGE_TAG && docker stop mohamedoweis/ticketingsystem || true && docker rm mohamedoweis/ticketingsystem || true && docker run -d --name mohamedoweis/ticketingsystem  mohamedoweis/ticketingsystem:$IMAGE_TAG"
















          



          
          
