name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get Version (Git Commit SHA and Date)
      run: echo "IMAGE_TAG=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mohamedoweis/ticketingsystem:latest
    - name: push image to docker hub
      run: |
          docker login -u mohamedoweis -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push mohamedoweis/ticketingsystem:latest  



          
          
