name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - '4EPlatform-TicketingSystem-FAQ-Development/Src/Services/Dockerfile'
      

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./4EPlatform-TicketingSystem-FAQ-Development/Src/Services/ -t mohamedoweis/ticketingfaq:latest
         
      - name: push image to docker hub
        run: |
          docker login -u mohamedoweis -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push mohamedoweis/ticketingfaq:latest
